import { createFileRoute } from "@tanstack/react-router";
import { managementSession } from "@/lib/management-auth.server";
import { getSql } from "@/lib/db";
import { qwen3VlModel, qwen3VlResponsesUrl, qwen3VlToken } from "@/lib/qwen3-vl.server";

const CATEGORIES = ["frete","adiantamento","pagamento","despesa","abastecimento","desconhecido"] as const;
type Category = typeof CATEGORIES[number];
type Reading={category:Category;confidence:number;documentType:string|null;documentNumber:string|null;date:string|null;time:string|null;amount:number|null;driverName:string|null;recipientName:string|null;tractorPlate:string|null;trailerPlate:string|null;supplier:string|null;description:string|null;ticketNumber:string|null;netWeightKg:number|null;freightMode:"ton"|"trip"|"cegonha"|"caixinha"|null;pricePerTon:number|null;pricePerTrip:number|null;origin:string|null;destination:string|null;client:string|null;categoryDetail:string|null;evidence:string[];warnings:string[]};

export const Route=createFileRoute("/api/teste-document-intake")({server:{handlers:{POST:async({request})=>{const session=await managementSession();if(!session)return json({ok:false,message:"Entre na Gerência novamente."},401);let body:any;try{body=await request.json()}catch{return json({ok:false,message:"Requisição inválida."},400)}const action=String(body?.action||"analyze");try{if(action==="list")return json({ok:true,items:await listPending()});if(action==="get")return json({ok:true,item:await getPending(String(body?.id||""))});if(action==="analyze")return json({ok:true,item:await analyzeAndSave(body,String(session.username||"Gerência"))});if(action==="update")return json({ok:true,item:await updatePending(body)});if(action==="reject")return json({ok:true,item:await changeStatus(String(body?.id||""),"recusado")});if(action==="confirm")return json({ok:true,result:await confirmPending(String(body?.id||""),body?.data)});return json({ok:false,message:"Ação desconhecida."},400)}catch(error){console.error("[teste-document-intake]",error);return json({ok:false,message:error instanceof Error?error.message:"Não foi possível concluir a operação."},500)}}}}});

function json(value:unknown,status=200){return Response.json(value,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
async function ensureTable(){const sql=await getSql();await sql`create table if not exists document_intake_pending(id text primary key,status text not null default 'pendente',category text not null,confidence numeric not null default 0,file_name text not null,mime text not null,file_base64 text not null,result_json jsonb not null,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`;await sql`create index if not exists document_intake_pending_status_idx on document_intake_pending(status,created_at desc)`;return sql}
async function listPending(){const sql=await ensureTable();const rows=await sql<any>`select id,status,category,confidence,file_name,mime,result_json,created_by,created_at,updated_at from document_intake_pending where status='pendente' order by created_at desc limit 100`;return rows.map(mapRow)}
async function getPending(id:string){if(!id)throw new Error("Documento pendente não informado.");const sql=await ensureTable();const rows=await sql<any>`select * from document_intake_pending where id=${id} limit 1`;if(!rows[0])throw new Error("Documento não encontrado.");return {...mapRow(rows[0]),base64:String(rows[0].file_base64||"")}}
async function analyzeAndSave(body:any,username:string){const fileName=cleanFileName(body?.fileName),mime=String(body?.mime||"").toLowerCase(),base64=String(body?.base64||"").replace(/\s+/g,"");validateFile(mime,base64);const key=await qwen3VlToken();if(!key)throw new Error("Leitura inteligente temporariamente indisponível. Tente novamente.");const reading=await analyzeDocument(key,fileName,mime,base64),sql=await ensureTable(),links=await resolveLinks(reading),enriched={...reading,...links},id="doc_test_"+crypto.randomUUID();await sql`insert into document_intake_pending(id,status,category,confidence,file_name,mime,file_base64,result_json,created_by) values(${id},'pendente',${reading.category},${reading.confidence},${fileName},${mime},${base64},${JSON.stringify(enriched)},${username})`;return{id,status:"pendente",fileName,mime,result:enriched}}
async function updatePending(body:any){const id=String(body?.id||"").trim();if(!id)throw new Error("Documento pendente não informado.");const sql=await ensureTable(),rows=await sql<any>`select * from document_intake_pending where id=${id} and status='pendente' limit 1`;if(!rows[0])throw new Error("Documento pendente não encontrado.");const next=sanitizeEdited({...parseResult(rows[0].result_json),...(body?.data||{})});await sql`update document_intake_pending set category=${next.category},confidence=${next.confidence},result_json=${JSON.stringify(next)},updated_at=now() where id=${id} and status='pendente'`;return{...mapRow(rows[0]),result:next}}
async function changeStatus(id:string,status:"recusado"){if(!id)throw new Error("Documento pendente não informado.");const sql=await ensureTable(),rows=await sql<any>`update document_intake_pending set status=${status},updated_at=now() where id=${id} and status='pendente' returning id,status`;if(!rows[0])throw new Error("Documento pendente não encontrado.");return rows[0]}
async function confirmPending(id:string,edits:any){if(!id)throw new Error("Documento pendente não informado.");const sql=await ensureTable(),rows=await sql<any>`select * from document_intake_pending where id=${id} and status='pendente' limit 1`;if(!rows[0])throw new Error("Documento pendente não encontrado.");const data=sanitizeEdited({...parseResult(rows[0].result_json),...(edits||{})}),result=await launchDocument(sql,data,String(rows[0].file_name||"documento"));await sql`update document_intake_pending set status='confirmado',result_json=${JSON.stringify(data)},updated_at=now() where id=${id} and status='pendente'`;return result}

async function launchDocument(sql:any,r:any,fileName:string){const category=normalizeCategory(r.category);if(!["frete","adiantamento","pagamento","despesa"].includes(category))throw new Error("Este documento precisa de revisão manual antes de ser lançado.");const date=validDate(r.date);if(!date)throw new Error("Informe a data da transação antes de confirmar.");const amount=positiveNumber(r.amount);
if(category==="frete"){if(!r.suggestedDriverId||!r.suggestedFleetId)throw new Error("Vincule o motorista e o conjunto antes de confirmar o frete.");const mode=r.freightMode;if(!mode)throw new Error("Informe a modalidade do frete.");const code=cleanText(r.ticketNumber||r.documentNumber||"",80)||await nextTicket(sql),collision=await sql`select id from trips where code=${code} limit 1`,finalCode=collision.length?await nextTicket(sql):code;let pricePerTon=positiveNumber(r.pricePerTon)||0,pricePerTrip=positiveNumber(r.pricePerTrip)||0;if(mode==="ton"){if(!positiveNumber(r.netWeightKg))throw new Error("Informe o peso líquido antes de confirmar o frete.");if(!pricePerTon)throw new Error("Informe o preço por tonelada antes de confirmar o frete.");}else if(!pricePerTrip){const configured=await sql`select price from freight_prices where mode=${mode} limit 1`;pricePerTrip=positiveNumber(configured[0]?.price)||0;if(!pricePerTrip)throw new Error("Configure ou informe o preço por viagem antes de confirmar.");}const idNew="trip_"+crypto.randomUUID(),tons=mode==="ton"?positiveNumber(r.netWeightKg)/1000:0;await sql`insert into trips(id,code,date,client,origin,destination,driver_id,fleet_id,loaded_tons,gross_weight,net_weight,freight_mode,price_per_ton,price_per_trip,diesel_liters,diesel_price,created_at) values(${idNew},${finalCode},${date},${cleanText(r.client,180)},${cleanText(r.origin,180)},${cleanText(r.destination,180)},${r.suggestedDriverId},${r.suggestedFleetId},${tons},0,${tons},${mode},${pricePerTon},${pricePerTrip},0,0,now())`;return{entity:"frete",id:idNew,message:`Frete lançado na viagem ${finalCode}.`}}
if(!amount)throw new Error("Informe o valor antes de confirmar.");
if(category==="adiantamento"){if(!r.suggestedDriverId)throw new Error("Vincule o motorista que recebeu o adiantamento antes de confirmar.");const duplicate=await sql`select id from expenses where category='Adiantamento' and driver_id=${r.suggestedDriverId} and date=${date} and amount=${amount} and coalesce(transaction_time,'')=coalesce(${validTime(r.time)},'') limit 1`;if(duplicate.length)throw new Error("Este adiantamento já existe no sistema.");const idNew="exp_"+crypto.randomUUID();await sql`insert into expenses(id,date,transaction_time,fleet_id,asset_type,driver_id,category,description,amount,notes) values(${idNew},${date},${validTime(r.time)},null,null,${r.suggestedDriverId},'Adiantamento',${cleanText(r.description,180)||"Adiantamento via comprovante"},${amount},${cleanText(r.notes||r.supplier,320)||fileName})`;return{entity:"adiantamento",id:idNew,message:"Adiantamento lançado em Pagamentos."}}
if(category==="pagamento"){if(!r.suggestedDriverId)throw new Error("Vincule o motorista que recebeu o pagamento antes de confirmar.");const note=cleanText(r.description,500)||"Pagamento via comprovante",duplicate=await sql`select id from driver_payments where driver_id=${r.suggestedDriverId} and payment_date=${date} and amount=${amount} and note=${note} limit 1`;if(duplicate.length)throw new Error("Este pagamento já existe no sistema.");const idNew="driver_payment_"+crypto.randomUUID();await sql`insert into driver_payments(id,driver_id,payment_date,amount,note,payment_type,period_start,period_end,created_by,created_at) values(${idNew},${r.suggestedDriverId},${date},${amount},${note},'payment',${date},${date},'TESTE',now())`;return{entity:"pagamento",id:idNew,message:"Pagamento lançado em Pagamentos."}}
if(!r.suggestedFleetId)throw new Error("Vincule o conjunto/veículo da despesa antes de confirmar.");const categoryName=cleanText(r.categoryDetail||"Outros",80)||"Outros",idNew="exp_"+crypto.randomUUID();await sql`insert into expenses(id,date,transaction_time,fleet_id,asset_type,driver_id,category,description,amount,notes) values(${idNew},${date},${validTime(r.time)},${r.suggestedFleetId},${r.suggestedAssetType==="trailer"?"trailer":"tractor"},null,${categoryName},${cleanText(r.description,180)||"Despesa via comprovante"},${amount},${cleanText(r.notes||r.supplier,320)||fileName})`;return{entity:"despesa",id:idNew,message:"Despesa lançada em Despesas."}}

async function analyzeDocument(key:string,fileName:string,mime:string,base64:string):Promise<Reading>{const ns={type:["string","null"]},nn={type:["number","null"]},schema={type:"object",additionalProperties:false,properties:{category:{type:"string",enum:CATEGORIES},confidence:{type:"number",minimum:0,maximum:1},document_type:ns,document_number:ns,date:ns,time:ns,amount:nn,driver_name:ns,recipient_name:ns,tractor_plate:ns,trailer_plate:ns,supplier:ns,description:ns,ticket_number:ns,net_weight_kg:nn,freight_mode:{type:["string","null"],enum:["ton","trip","cegonha","caixinha",null]},price_per_ton:nn,price_per_trip:nn,origin:ns,destination:ns,client:ns,category_detail:ns,evidence:{type:"array",items:{type:"string"},maxItems:8},warnings:{type:"array",items:{type:"string"},maxItems:8}},required:["category","confidence","document_type","document_number","date","time","amount","driver_name","recipient_name","tractor_plate","trailer_plate","supplier","description","ticket_number","net_weight_kg","freight_mode","price_per_ton","price_per_trip","origin","destination","client","category_detail","evidence","warnings"]};const instructions=`Você é o classificador visual da Trans Salomão. Analise somente o que está visível na foto/PDF. Nunca invente dados.

CLASSIFIQUE EXATAMENTE EM UMA CATEGORIA:
- frete: ticket de balança, romaneio ou comprovante claramente ligado a uma viagem/frete.
- adiantamento: dinheiro/PIX/transferência cujo recebedor é motorista e representa adiantamento.
- pagamento: dinheiro/PIX/transferência ao motorista que não é claramente adiantamento.
- despesa: nota, recibo ou comprovante de gasto da empresa.
- abastecimento: posto/diesel/combustível com litros e preço por litro.
- desconhecido: ilegível ou sem evidência suficiente.

REGRAS: confidence reflete a evidência real; não use o nome do arquivo; amount é o valor efetivamente pago; date/time somente se impressos como data/hora da transação; recipient_name é quem recebeu; para frete por tonelada, net_weight_kg é obrigatório; 38,470 t = 38470 kg; cegonha com Romaneio/Data Embarque/PESO-KG/VALOR/QUANTIDADE usa freight_mode=cegonha e ticket_number=Romaneio, sem tratar PESO-KG como peso líquido; despesas usam Manutenção, Peças, Pneus, Elétrica, Mecânica, Lavagem, Documentação, Seguro, Pedágio, Multa ou Outros; placas somente se visíveis; preserve centavos; evidence e warnings devem ser objetivos.`;const content=mime==="application/pdf"?[{type:"input_text",text:"Classifique este documento e extraia os campos visíveis."},{type:"input_file",filename:fileName,file_data:`data:application/pdf;base64,${base64}`}]:[{type:"input_text",text:"Classifique esta imagem e extraia os campos visíveis."},{type:"input_image",image_url:`data:${mime};base64,${base64}`,detail:"high"}];const response=await fetch(qwen3VlResponsesUrl(),{method:"POST",signal:AbortSignal.timeout(60000),headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:qwen3VlModel(),instructions,input:[{role:"user",content}],text:{format:{type:"json_schema",name:"trans_salomao_teste_document",strict:true,schema}},max_output_tokens:1600})});const data:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Leitor visual ${response.status}: ${JSON.stringify(data).slice(0,400)}`);const raw=outputText(data);if(!raw)throw new Error("A leitura retornou vazia.");return normalizeReading(JSON.parse(raw))}
function outputText(data:any){if(typeof data?.output_text==="string"&&data.output_text.trim())return data.output_text.trim();const parts:string[]=[];for(const item of Array.isArray(data?.output)?data.output:[])for(const part of Array.isArray(item?.content)?item.content:[])if(part?.type==="output_text"&&typeof part.text==="string")parts.push(part.text);return parts.join("").trim()}
function normalizeReading(v:any):Reading{return{category:CATEGORIES.includes(v?.category)?v.category:"desconhecido",confidence:clamp(Number(v?.confidence)||0),documentType:cleanNullable(v?.document_type,120),documentNumber:cleanNullable(v?.document_number,100),date:validDate(v?.date),time:validTime(v?.time),amount:positiveNumber(v?.amount),driverName:cleanNullable(v?.driver_name,180),recipientName:cleanNullable(v?.recipient_name,180),tractorPlate:normalizePlate(v?.tractor_plate),trailerPlate:normalizePlate(v?.trailer_plate),supplier:cleanNullable(v?.supplier,180),description:cleanNullable(v?.description,180),ticketNumber:cleanNullable(v?.ticket_number,100),netWeightKg:positiveNumber(v?.net_weight_kg),freightMode:["ton","trip","cegonha","caixinha"].includes(v?.freight_mode)?v.freight_mode:null,pricePerTon:positiveNumber(v?.price_per_ton),pricePerTrip:positiveNumber(v?.price_per_trip),origin:cleanNullable(v?.origin,180),destination:cleanNullable(v?.destination,180),client:cleanNullable(v?.client,180),categoryDetail:cleanNullable(v?.category_detail,80),evidence:Array.isArray(v?.evidence)?v.evidence.map((x:any)=>cleanText(x,180)).filter(Boolean).slice(0,8):[],warnings:Array.isArray(v?.warnings)?v.warnings.map((x:any)=>cleanText(x,180)).filter(Boolean).slice(0,8):[]}}
async function resolveLinks(r:Reading){const sql=await getSql(),drivers=await sql<any>`select id,name from drivers where status='ativo' order by name`,fleets=await sql<any>`select id,name,tractor_plate,trailer_plate from fleets where status='ativo' order by name`;const driver=matchDriver([r.driverName,r.recipientName],drivers),fleet=matchFleet([r.tractorPlate,r.trailerPlate],fleets);return{suggestedDriverId:driver?.id?String(driver.id):null,suggestedDriverName:driver?.name?String(driver.name):null,suggestedFleetId:fleet?.id?String(fleet.id):null,suggestedFleetName:fleet?.name?String(fleet.name):null,suggestedAssetType:fleet?.assetType||null}}
function matchDriver(hints:Array<string|null>,rows:any[]){const wanted=hints.map(normalizeText).filter(x=>x.length>=3),scored=rows.map(row=>{const name=normalizeText(row?.name);let score=0;for(const hint of wanted){if(hint===name)score=Math.max(score,1);else if(hint.length>=6&&name.length>=6&&(hint.includes(name)||name.includes(hint)))score=Math.max(score,.94);else{const a=new Set(hint.split(" ").filter(x=>x.length>=3)),b=name.split(" ").filter(x=>x.length>=3),shared=b.filter(x=>a.has(x)).length;if(b.length&&shared>=2)score=Math.max(score,shared/b.length)}}return{row,score}}).filter(x=>x.score>=.78).sort((a,b)=>b.score-a.score);return scored.length&&(scored.length===1||scored[0].score-scored[1].score>=.12)?scored[0].row:null}
function matchFleet(plates:string[],rows:any[]){const wanted=plates.map(normalizePlate).filter(Boolean),matches=rows.flatMap(row=>{const out:any[]=[];if(wanted.includes(normalizePlate(row?.tractor_plate)))out.push({row,assetType:"tractor"});if(wanted.includes(normalizePlate(row?.trailer_plate)))out.push({row,assetType:"trailer"});return out});return matches.length===1?{...matches[0].row,assetType:matches[0].assetType}:null}
function mapRow(row:any){return{id:String(row.id),status:String(row.status),category:String(row.category),confidence:Number(row.confidence||0),fileName:String(row.file_name||""),mime:String(row.mime||""),result:parseResult(row.result_json),createdBy:row.created_by==null?null:String(row.created_by),createdAt:String(row.created_at||"")}}
function parseResult(v:any){if(typeof v==="string"){try{return JSON.parse(v)}catch{}}return v||{}}
function sanitizeEdited(v:any){return{...v,category:normalizeCategory(v?.category),confidence:clamp(Number(v?.confidence)||0),amount:positiveNumber(v?.amount),date:validDate(v?.date),time:validTime(v?.time),suggestedDriverId:cleanNullable(v?.suggestedDriverId,100),suggestedDriverName:cleanNullable(v?.suggestedDriverName,180),suggestedFleetId:cleanNullable(v?.suggestedFleetId,100),suggestedFleetName:cleanNullable(v?.suggestedFleetName,180),suggestedAssetType:v?.suggestedAssetType==="trailer"?"trailer":v?.suggestedAssetType==="tractor"?"tractor":null,netWeightKg:positiveNumber(v?.netWeightKg),pricePerTon:positiveNumber(v?.pricePerTon),pricePerTrip:positiveNumber(v?.pricePerTrip)}}
function normalizeCategory(v:any):Category{return CATEGORIES.includes(v)?v:"desconhecido"}
function validateFile(mime:string,base64:string){if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(mime))throw new Error("Use foto JPG, PNG, WebP ou PDF.");if(!base64||base64.length>4000000||!/^[A-Za-z0-9+/]+={0,2}$/.test(base64))throw new Error("Arquivo vazio, inválido ou grande demais.");const bytes=Buffer.from(base64,"base64");if(bytes.length<12)throw new Error("Arquivo inválido.");const valid=(mime==="application/pdf"&&bytes.toString("ascii",0,4)==="%PDF")||(mime==="image/jpeg"&&bytes.subarray(0,3).equals(Buffer.from([255,216,255])))||(mime==="image/png"&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(mime==="image/webp"&&bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP");if(!valid)throw new Error("O conteúdo do arquivo não corresponde ao formato informado.")}
function cleanFileName(v:any){return String(v||"documento").replace(/[\r\n\t]/g," ").replace(/\s+/g," ").trim().slice(0,160)}
function cleanText(v:any,max=500){return String(v??"").replace(/[\r\n\t]/g," ").replace(/\s+/g," ").trim().slice(0,max)}
function cleanNullable(v:any,max=180){const s=cleanText(v,max);return s||null}
function normalizeText(v:any){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR").replace(/[^a-z0-9]+/g," ").trim()}
function normalizePlate(v:any){const p=String(v??"").toUpperCase().replace(/[^A-Z0-9]/g,"");return/^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$/.test(p)?p:null}
function validDate(v:any){const s=String(v??"").trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return null;const d=new Date(s+"T12:00:00Z");return Number.isNaN(d.getTime())?null:s}
function validTime(v:any){const s=String(v??"").trim(),m=s.match(/^([01]\d|2[0-3]):([0-5]\d)(?::[0-5]\d)?$/);return m?m[1]+":"+m[2]:null}
function positiveNumber(v:any){const n=Number(v);return Number.isFinite(n)&&n>0&&n<=100000000?n:null}
function clamp(n:number){return Math.max(0,Math.min(1,n))}
async function nextTicket(sql:any){const rows=await sql`select code from trips order by created_at desc nulls last limit 1`;const last=String(rows[0]?.code||""),n=Number(last.replace(/\D/g,""));return String(Number.isFinite(n)&&n>0?n+1:Date.now())}
