plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.transsalomao.app'
    compileSdk 35

    defaultConfig {
        applicationId "br.com.transsalomao.app"
        minSdk 24
        targetSdk 35
        versionCode 2026092703
        versionName "2026.09.27.3"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
}
