/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonoRouteRouteImport } from './routes/dono/route'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as DonoIndexRouteImport } from './routes/dono/index'
import { Route as DonoAbastecimentosRouteImport } from './routes/dono/abastecimentos'
import { Route as DonoCadastrosRouteImport } from './routes/dono/cadastros'
import { Route as DonoDespesasRouteImport } from './routes/dono/despesas'
import { Route as DonoLancamentosRouteImport } from './routes/dono/lancamentos'
import { Route as DonoTotaisRouteImport } from './routes/dono/totais'
import { Route as DonoViagensRouteImport } from './routes/dono/viagens'
import { Route as DonoTesteRouteImport } from './routes/dono/teste'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoRouteRoute = DonoRouteRouteImport.update({
  id: '/dono',
  path: '/dono',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoIndexRoute = DonoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonoRouteRoute,
} as any)
const DonoAbastecimentosRoute = DonoAbastecimentosRouteImport.update({
  id: '/abastecimentos',
  path: '/abastecimentos',
  getParentRoute: () => DonoRouteRoute,
} as any)
const DonoCadastrosRoute = DonoCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => DonoRouteRoute,
} as any)
const DonoDespesasRoute = DonoDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => DonoRouteRoute,
} as any)
const DonoLancamentosRoute = DonoLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => DonoRouteRoute,
} as any)
const DonoTotaisRoute = DonoTotaisRouteImport.update({
  id: '/totais',
  path: '/totais',
  getParentRoute: () => DonoRouteRoute,
} as any)
const DonoViagensRoute = DonoViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => DonoRouteRoute,
} as any)
const DonoTesteRoute = DonoTesteRouteImport.update({
  id: '/teste',
  path: '/teste',
  getParentRoute: () => DonoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dono': typeof DonoRouteRouteWithChildren
  '/motorista': typeof MotoristaRoute
  '/dono/abastecimentos': typeof DonoAbastecimentosRoute
  '/dono/cadastros': typeof DonoCadastrosRoute
  '/dono/despesas': typeof DonoDespesasRoute
  '/dono/lancamentos': typeof DonoLancamentosRoute
  '/dono/totais': typeof DonoTotaisRoute
  '/dono/viagens': typeof DonoViagensRoute
  '/dono/teste': typeof DonoTesteRoute
  '/dono/': typeof DonoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dono/abastecimentos': typeof DonoAbastecimentosRoute
  '/dono/cadastros': typeof DonoCadastrosRoute
  '/dono/despesas': typeof DonoDespesasRoute
  '/dono/lancamentos': typeof DonoLancamentosRoute
  '/dono/totais': typeof DonoTotaisRoute
  '/dono/viagens': typeof DonoViagensRoute
  '/dono/teste': typeof DonoTesteRoute
  '/dono': typeof DonoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dono': typeof DonoRouteRouteWithChildren
  '/motorista': typeof MotoristaRoute
  '/dono/abastecimentos': typeof DonoAbastecimentosRoute
  '/dono/cadastros': typeof DonoCadastrosRoute
  '/dono/despesas': typeof DonoDespesasRoute
  '/dono/lancamentos': typeof DonoLancamentosRoute
  '/dono/totais': typeof DonoTotaisRoute
  '/dono/viagens': typeof DonoViagensRoute
  '/dono/teste': typeof DonoTesteRoute
  '/dono/': typeof DonoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dono'
    | '/motorista'
    | '/dono/abastecimentos'
    | '/dono/cadastros'
    | '/dono/despesas'
    | '/dono/lancamentos'
    | '/dono/totais'
    | '/dono/viagens'
    | '/dono/teste'
    | '/dono/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dono/abastecimentos'
    | '/dono/cadastros'
    | '/dono/despesas'
    | '/dono/lancamentos'
    | '/dono/totais'
    | '/dono/viagens'
    | '/dono/teste'
    | '/dono'
  id:
    | '__root__'
    | '/'
    | '/dono'
    | '/motorista'
    | '/dono/abastecimentos'
    | '/dono/cadastros'
    | '/dono/despesas'
    | '/dono/lancamentos'
    | '/dono/totais'
    | '/dono/viagens'
    | '/dono/teste'
    | '/dono/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonoRouteRoute: typeof DonoRouteRouteWithChildren
  MotoristaRoute: typeof MotoristaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono': {
      id: '/dono'
      path: '/dono'
      fullPath: '/dono'
      preLoaderRoute: typeof DonoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/': {
      id: '/dono/'
      path: '/'
      fullPath: '/dono/'
      preLoaderRoute: typeof DonoIndexRouteImport
      parentRoute: typeof DonoRouteRoute
    }
    '/dono/abastecimentos': {
      id: '/dono/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/dono/abastecimentos'
      preLoaderRoute: typeof DonoAbastecimentosRouteImport
      parentRoute: typeof DonoRouteRoute
    }
    '/dono/cadastros': {
      id: '/dono/cadastros'
      path: '/cadastros'
      fullPath: '/dono/cadastros'
      preLoaderRoute: typeof DonoCadastrosRouteImport
      parentRoute: typeof DonoRouteRoute
    }
    '/dono/despesas': {
      id: '/dono/despesas'
      path: '/despesas'
      fullPath: '/dono/despesas'
      preLoaderRoute: typeof DonoDespesasRouteImport
      parentRoute: typeof DonoRouteRoute
    }
    '/dono/lancamentos': {
      id: '/dono/lancamentos'
      path: '/lancamentos'
      fullPath: '/dono/lancamentos'
      preLoaderRoute: typeof DonoLancamentosRouteImport
      parentRoute: typeof DonoRouteRoute
    }
    '/dono/totais': {
      id: '/dono/totais'
      path: '/totais'
      fullPath: '/dono/totais'
      preLoaderRoute: typeof DonoTotaisRouteImport
      parentRoute: typeof DonoRouteRoute
    }
    '/dono/viagens': {
      id: '/dono/viagens'
      path: '/viagens'
      fullPath: '/dono/viagens'
      preLoaderRoute: typeof DonoViagensRouteImport
      parentRoute: typeof DonoRouteRoute
    }
    '/dono/teste': {
      id: '/dono/teste'
      path: '/teste'
      fullPath: '/dono/teste'
      preLoaderRoute: typeof DonoTesteRouteImport
      parentRoute: typeof DonoRouteRoute
    }
  }
}

interface DonoRouteRouteChildren {
  DonoAbastecimentosRoute: typeof DonoAbastecimentosRoute
  DonoCadastrosRoute: typeof DonoCadastrosRoute
  DonoDespesasRoute: typeof DonoDespesasRoute
  DonoLancamentosRoute: typeof DonoLancamentosRoute
  DonoTotaisRoute: typeof DonoTotaisRoute
  DonoViagensRoute: typeof DonoViagensRoute
  DonoTesteRoute: typeof DonoTesteRoute
  DonoIndexRoute: typeof DonoIndexRoute
}

const DonoRouteRouteChildren: DonoRouteRouteChildren = {
  DonoAbastecimentosRoute: DonoAbastecimentosRoute,
  DonoCadastrosRoute: DonoCadastrosRoute,
  DonoDespesasRoute: DonoDespesasRoute,
  DonoLancamentosRoute: DonoLancamentosRoute,
  DonoTotaisRoute: DonoTotaisRoute,
  DonoViagensRoute: DonoViagensRoute,
  DonoTesteRoute: DonoTesteRoute,
  DonoIndexRoute: DonoIndexRoute,
}

const DonoRouteRouteWithChildren = DonoRouteRoute._addFileChildren(
  DonoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonoRouteRoute: DonoRouteRouteWithChildren,
  MotoristaRoute: MotoristaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
