package com.wifiguard.enterprise;

import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.content.BroadcastReceiver;import android.content.Context;import android.content.Intent;import android.content.IntentFilter;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.Typeface;import android.net.DhcpInfo;import android.net.wifi.ScanResult;import android.net.wifi.WifiManager;import android.os.Build;import android.os.Bundle;import android.text.InputType;import android.view.View;import android.view.ViewGroup;import android.widget.Button;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;
import java.io.InputStream;import java.net.InetSocketAddress;import java.net.Socket;import java.util.ArrayList;import java.util.Collections;import java.util.HashMap;import java.util.List;import java.util.Locale;import java.util.Map;import java.util.concurrent.ExecutorService;import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private static final int REQ_PERMS=10,REQ_PCAP=11; private final ExecutorService executor=Executors.newSingleThreadExecutor(); private WifiManager wifi; private LinearLayout resultsBox; private TextView status; private StringBuilder report=new StringBuilder(); private BroadcastReceiver scanReceiver;
    @Override protected void onCreate(Bundle b){super.onCreate(b);wifi=(WifiManager)getApplicationContext().getSystemService(Context.WIFI_SERVICE);setContentView(buildUi());scanReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){renderScanResults();}};IntentFilter f=new IntentFilter(WifiManager.SCAN_RESULTS_AVAILABLE_ACTION);if(Build.VERSION.SDK_INT>=33)registerReceiver(scanReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(scanReceiver,f);}
    private View buildUi(){ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(18),dp(16),dp(32));root.setBackgroundColor(Color.rgb(245,247,250));scroll.addView(root);root.addView(text("WiFi Guard Enterprise",27,true,Color.rgb(11,18,32)));TextView sub=text("Auditoria Wi‑Fi defensiva • scanner • WPS/WPA • PCAP/EAPOL • laboratório seguro",14,false,Color.DKGRAY);sub.setPadding(0,dp(4),0,dp(14));root.addView(sub);LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.VERTICAL);root.addView(buttons,matchWrap());buttons.addView(button("Escanear redes Wi‑Fi",v->startWifiScan()));buttons.addView(button("Auditar rede conectada",v->auditGateway()));buttons.addView(button("Analisar PCAP / handshake",v->choosePcap()));buttons.addView(button("Laboratório seguro",v->showLab()));buttons.addView(button("Compartilhar relatório",v->shareReport()));status=text("Pronto. Conceda as permissões e inicie a varredura.",14,false,Color.rgb(60,70,85));status.setPadding(0,dp(16),0,dp(10));root.addView(status);resultsBox=new LinearLayout(this);resultsBox.setOrientation(LinearLayout.VERTICAL);root.addView(resultsBox,matchWrap());TextView n=text("Importante: o app não transmite deauth, não tenta PINs WPS e não quebra senhas reais. O laboratório é sintético; PCAP é analisado offline.",12,false,Color.rgb(90,90,90));n.setPadding(0,dp(18),0,0);root.addView(n);return scroll;}
    private void startWifiScan(){if(!hasWifiPermissions()){requestWifiPermissions();return;}status.setText("Solicitando varredura…");try{boolean started=wifi.startScan();if(!started){status.setText("O Android limitou uma nova varredura. Exibindo os resultados disponíveis.");renderScanResults();}}catch(SecurityException e){status.setText("Permissão insuficiente: "+e.getMessage());}}
    private boolean hasWifiPermissions(){boolean fine=checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;boolean nearby=Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.NEARBY_WIFI_DEVICES)==PackageManager.PERMISSION_GRANTED;return fine&&nearby;}
    private void requestWifiPermissions(){ArrayList<String> p=new ArrayList<>();p.add(Manifest.permission.ACCESS_FINE_LOCATION);if(Build.VERSION.SDK_INT>=33)p.add(Manifest.permission.NEARBY_WIFI_DEVICES);requestPermissions(p.toArray(new String[0]),REQ_PERMS);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_PERMS&&hasWifiPermissions())startWifiScan();else if(r==REQ_PERMS)status.setText("Permissão negada. A varredura Wi‑Fi não pode ser executada.");}
    private void renderScanResults(){if(!hasWifiPermissions())return;List<ScanResult> list;try{list=new ArrayList<>(wifi.getScanResults());}catch(SecurityException e){status.setText("Sem acesso aos resultados: "+e.getMessage());return;}Collections.sort(list,(a,b)->Integer.compare(b.level,a.level));resultsBox.removeAllViews();report=new StringBuilder("WiFi Guard Enterprise — relatório\n\n");Map<String,String> ssidSecurity=new HashMap<>();int critical=0,high=0;for(ScanResult r:list){WifiSecurityAnalyzer.AuditResult a=WifiSecurityAnalyzer.analyze(r);if(a.score<40)critical++;else if(a.score<65)high++;String ssid=(r.SSID==null||r.SSID.isEmpty())?"<SSID oculto>":r.SSID;String previous=ssidSecurity.putIfAbsent(ssid,a.security);boolean inconsistent=previous!=null&&!previous.equals(a.security);addNetworkCard(r,a,inconsistent);report.append(networkText(r,a,inconsistent)).append("\n");}status.setText(String.format(Locale.US,"%d redes encontradas • %d críticas • %d de risco alto",list.size(),critical,high));if(list.isEmpty())resultsBox.addView(text("Nenhum resultado. Verifique Wi‑Fi e Localização e tente novamente.",14,false,Color.DKGRAY));}
    private void addNetworkCard(ScanResult r,WifiSecurityAnalyzer.AuditResult a,boolean inconsistent){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(12),dp(14),dp(12));android.graphics.drawable.GradientDrawable bg=new android.graphics.drawable.GradientDrawable();bg.setColor(Color.WHITE);bg.setCornerRadius(dp(14));bg.setStroke(dp(1),Color.rgb(220,225,232));card.setBackground(bg);LinearLayout.LayoutParams cp=matchWrap();cp.setMargins(0,0,0,dp(10));String ssid=(r.SSID==null||r.SSID.isEmpty())?"<SSID oculto>":r.SSID;card.addView(text(ssid,18,true,Color.rgb(17,24,39)));int ch=WifiSecurityAnalyzer.channel(r.frequency);card.addView(text(a.security+"  •  "+r.level+" dBm  •  "+WifiSecurityAnalyzer.band(r.frequency)+(ch>0?" / canal "+ch:""),13,false,Color.DKGRAY));card.addView(text("Score "+a.score+"/100 — "+WifiSecurityAnalyzer.riskLabel(a.score)+(a.wps?"  •  WPS detectado":""),14,true,a.score<40?Color.rgb(180,30,30):(a.score<65?Color.rgb(190,105,0):Color.rgb(20,110,60))));if(inconsistent)card.addView(text("⚠ Mesmo SSID apareceu com segurança diferente: revisar possível AP imitador.",12,true,Color.rgb(180,80,0)));card.setOnClickListener(v->showNetworkDetails(r,a,inconsistent));resultsBox.addView(card,cp);}
    private String networkText(ScanResult r,WifiSecurityAnalyzer.AuditResult a,boolean inconsistent){String ssid=(r.SSID==null||r.SSID.isEmpty())?"<SSID oculto>":r.SSID;StringBuilder b=new StringBuilder();b.append(ssid).append(" | ").append(r.BSSID).append(" | ").append(a.security).append(" | score ").append(a.score).append(" | ").append(r.level).append(" dBm | ").append(r.frequency).append(" MHz\n");if(inconsistent)b.append("  ALERTA: segurança inconsistente para o mesmo SSID.\n");for(String f:a.findings)b.append("  - ").append(f).append("\n");return b.toString();}
    private void showNetworkDetails(ScanResult r,WifiSecurityAnalyzer.AuditResult a,boolean inconsistent){StringBuilder b=new StringBuilder();b.append("SSID: ").append(r.SSID).append("\nBSSID: ").append(r.BSSID).append("\nSegurança: ").append(a.security).append("\nScore: ").append(a.score).append("/100 — ").append(WifiSecurityAnalyzer.riskLabel(a.score)).append("\nSinal: ").append(r.level).append(" dBm\nFrequência: ").append(r.frequency).append(" MHz\nCanal: ").append(WifiSecurityAnalyzer.channel(r.frequency)).append("\nWPS: ").append(a.wps?"detectado":"não identificado").append("\nPMF: ").append(a.pmfRequired?"obrigatório":(a.pmfCapable?"capaz":"não identificado")).append("\n\nAchados:\n");if(inconsistent)b.append("• Possível configuração inconsistente/SSID imitador.\n");for(String f:a.findings)b.append("• ").append(f).append("\n");b.append("\nCapabilities brutas:\n").append(r.capabilities);new AlertDialog.Builder(this).setTitle("Auditoria da rede").setMessage(b.toString()).setPositiveButton("OK",null).show();}
    private void choosePcap(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_PCAP);}
    @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==REQ_PCAP&&result==RESULT_OK&&data!=null&&data.getData()!=null){status.setText("Analisando PCAP offline…");executor.execute(()->{try(InputStream in=getContentResolver().openInputStream(data.getData())){PcapAnalyzer.Result x=PcapAnalyzer.analyze(in);String msg="EAPOL-Key: "+x.eapolFrames+"\nM1: "+x.m1+"  M2: "+x.m2+"  M3: "+x.m3+"  M4: "+x.m4+"\n4-way completo: "+(x.complete4Way?"SIM":"NÃO")+"\n\n"+x.note+"\n\nA análise não tenta descobrir a senha.";report.append("\nPCAP\n").append(msg).append("\n");runOnUiThread(()->{status.setText("PCAP analisado.");new AlertDialog.Builder(this).setTitle("Resultado do handshake").setMessage(msg).setPositiveButton("OK",null).show();});}catch(Exception e){runOnUiThread(()->status.setText("Falha ao analisar PCAP: "+e.getMessage()));}});}}
    private void showLab(){EditText input=new EditText(this);input.setHint("Segredo de treino (não use credencial real)");input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Laboratório de resistência").setMessage("Simula dicionário, WPS, WEP e deauth sem transmitir pacotes.").setView(input).setPositiveButton("Executar",(d,w)->{String out=LabSimulator.run(input.getText().toString());report.append("\nLABORATÓRIO\n").append(out).append("\n");new AlertDialog.Builder(this).setTitle("Resultado do laboratório").setMessage(out).setPositiveButton("OK",null).show();}).setNegativeButton("Cancelar",null).show();}
    private void auditGateway(){if(!hasWifiPermissions()){requestWifiPermissions();return;}DhcpInfo dhcp=wifi.getDhcpInfo();if(dhcp==null||dhcp.gateway==0){status.setText("Gateway não identificado. Conecte-se à rede da empresa.");return;}String host=intToIp(dhcp.gateway);status.setText("Auditando exposição básica do gateway "+host+"…");executor.execute(()->{int[] ports={22,23,53,80,443,8080,8443};StringBuilder b=new StringBuilder("Gateway: ").append(host).append("\n");for(int p:ports)b.append("TCP ").append(p).append(": ").append(isOpen(host,p)?"ABERTO":"fechado/não respondeu").append("\n");b.append("\nPortas abertas não significam vulnerabilidade por si só; restrinja gestão e prefira HTTPS/SSH.");report.append("\nGATEWAY\n").append(b).append("\n");runOnUiThread(()->{status.setText("Auditoria básica do gateway concluída.");new AlertDialog.Builder(this).setTitle("Serviços do gateway").setMessage(b.toString()).setPositiveButton("OK",null).show();});});}
    private boolean isOpen(String h,int p){try(Socket s=new Socket()){s.connect(new InetSocketAddress(h,p),450);return true;}catch(Exception e){return false;}}
    private String intToIp(int x){return(x&0xff)+"."+((x>>8)&0xff)+"."+((x>>16)&0xff)+"."+((x>>24)&0xff);}
    private void shareReport(){if(report.length()<30){Toast.makeText(this,"Execute uma auditoria primeiro.",Toast.LENGTH_SHORT).show();return;}Intent s=new Intent(Intent.ACTION_SEND);s.setType("text/plain");s.putExtra(Intent.EXTRA_SUBJECT,"Relatório WiFi Guard Enterprise");s.putExtra(Intent.EXTRA_TEXT,report.toString());startActivity(Intent.createChooser(s,"Compartilhar relatório"));}
    private Button button(String l,View.OnClickListener x){Button b=new Button(this);b.setText(l);b.setAllCaps(false);b.setTextSize(15);b.setOnClickListener(x);LinearLayout.LayoutParams p=matchWrap();p.setMargins(0,0,0,dp(7));b.setLayoutParams(p);return b;}
    private TextView text(String s,int sp,boolean bold,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private LinearLayout.LayoutParams matchWrap(){return new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);} private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    @Override protected void onDestroy(){try{unregisterReceiver(scanReceiver);}catch(Exception ignored){}executor.shutdownNow();super.onDestroy();}
}
